"""empty message

Revision ID: 1027ba3885
Revises: d7cff3beda
Create Date: 2016-01-25 08:53:41.536710

"""

# revision identifiers, used by Alembic.
revision = '1027ba3885'
down_revision = 'd7cff3beda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
