"""empty message

Revision ID: 11c44cd25a1
Revises: 51b706eff65
Create Date: 2016-01-25 08:47:39.527158

"""

# revision identifiers, used by Alembic.
revision = '11c44cd25a1'
down_revision = '51b706eff65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
