"""empty message

Revision ID: 13401c53224
Revises: 5f86ac3fe1
Create Date: 2016-01-25 08:49:04.120960

"""

# revision identifiers, used by Alembic.
revision = '13401c53224'
down_revision = '5f86ac3fe1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
