"""empty message

Revision ID: 19088bd14c8
Revises: 2547e767d7f
Create Date: 2016-01-25 08:55:44.457113

"""

# revision identifiers, used by Alembic.
revision = '19088bd14c8'
down_revision = '2547e767d7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
