"""empty message

Revision ID: 1bf8e44d95e
Revises: 495d608c1c9
Create Date: 2016-01-25 08:49:43.930574

"""

# revision identifiers, used by Alembic.
revision = '1bf8e44d95e'
down_revision = '495d608c1c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
