"""empty message

Revision ID: 1d5d5a55651
Revises: 27641fd758f
Create Date: 2016-01-25 08:51:01.938647

"""

# revision identifiers, used by Alembic.
revision = '1d5d5a55651'
down_revision = '27641fd758f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
