"""empty message

Revision ID: 214cd9dc6bf
Revises: 3add22afef4
Create Date: 2016-01-25 08:48:00.285781

"""

# revision identifiers, used by Alembic.
revision = '214cd9dc6bf'
down_revision = '3add22afef4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
