"""empty message

Revision ID: 24bac84032d
Revises: 1027ba3885
Create Date: 2016-01-25 08:54:09.677274

"""

# revision identifiers, used by Alembic.
revision = '24bac84032d'
down_revision = '1027ba3885'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
