"""empty message

Revision ID: 2547e767d7f
Revises: e8b14528b7
Create Date: 2016-01-25 08:55:17.522937

"""

# revision identifiers, used by Alembic.
revision = '2547e767d7f'
down_revision = 'e8b14528b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
