"""empty message

Revision ID: 27641fd758f
Revises: 4ffa154631b
Create Date: 2016-01-25 08:50:35.775871

"""

# revision identifiers, used by Alembic.
revision = '27641fd758f'
down_revision = '4ffa154631b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
