"""empty message

Revision ID: 292cabc65f4
Revises: 526cc9db974
Create Date: 2016-01-25 08:48:49.353122

"""

# revision identifiers, used by Alembic.
revision = '292cabc65f4'
down_revision = '526cc9db974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
