"""empty message

Revision ID: 2c69f0af10b
Revises: 3aa24c78cbe
Create Date: 2016-01-25 08:48:28.506945

"""

# revision identifiers, used by Alembic.
revision = '2c69f0af10b'
down_revision = '3aa24c78cbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
