"""empty message

Revision ID: 2ceaaaa8235
Revises: 4d8775c32d0
Create Date: 2016-01-25 09:02:34.970214

"""

# revision identifiers, used by Alembic.
revision = '2ceaaaa8235'
down_revision = '4d8775c32d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
