"""empty message

Revision ID: 2d01c3e9d90
Revises: 19088bd14c8
Create Date: 2016-01-25 09:01:17.791333

"""

# revision identifiers, used by Alembic.
revision = '2d01c3e9d90'
down_revision = '19088bd14c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
