"""empty message

Revision ID: 2efe2037488
Revises: 2c69f0af10b
Create Date: 2016-01-25 08:48:36.752609

"""

# revision identifiers, used by Alembic.
revision = '2efe2037488'
down_revision = '2c69f0af10b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
