"""empty message

Revision ID: 308d95eada6
Revises: 4ff347aaf3b
Create Date: 2016-01-25 09:07:21.533575

"""

# revision identifiers, used by Alembic.
revision = '308d95eada6'
down_revision = '4ff347aaf3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
