"""empty message

Revision ID: 34783216963
Revises: 292cabc65f4
Create Date: 2016-01-25 08:48:50.683488

"""

# revision identifiers, used by Alembic.
revision = '34783216963'
down_revision = '292cabc65f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
