"""empty message

Revision ID: 3aa24c78cbe
Revises: 52126c8a30e
Create Date: 2016-01-25 08:48:26.739686

"""

# revision identifiers, used by Alembic.
revision = '3aa24c78cbe'
down_revision = '52126c8a30e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
