"""empty message

Revision ID: 3add22afef4
Revises: 11c44cd25a1
Create Date: 2016-01-25 08:47:46.718581

"""

# revision identifiers, used by Alembic.
revision = '3add22afef4'
down_revision = '11c44cd25a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
