"""empty message

Revision ID: 3f858e4dc78
Revises: 765a23fa25
Create Date: 2016-01-25 09:08:48.339791

"""

# revision identifiers, used by Alembic.
revision = '3f858e4dc78'
down_revision = '765a23fa25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
