"""empty message

Revision ID: 44f9b10a927
Revises: 1d5d5a55651
Create Date: 2016-01-25 08:51:52.052978

"""

# revision identifiers, used by Alembic.
revision = '44f9b10a927'
down_revision = '1d5d5a55651'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
