"""empty message

Revision ID: 495d608c1c9
Revises: 13401c53224
Create Date: 2016-01-25 08:49:17.030514

"""

# revision identifiers, used by Alembic.
revision = '495d608c1c9'
down_revision = '13401c53224'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
