"""empty message

Revision ID: 4d8775c32d0
Revises: 2d01c3e9d90
Create Date: 2016-01-25 09:02:07.798157

"""

# revision identifiers, used by Alembic.
revision = '4d8775c32d0'
down_revision = '2d01c3e9d90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
