"""empty message

Revision ID: 4ff347aaf3b
Revises: 2ceaaaa8235
Create Date: 2016-01-25 09:06:49.314229

"""

# revision identifiers, used by Alembic.
revision = '4ff347aaf3b'
down_revision = '2ceaaaa8235'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
