"""empty message

Revision ID: 4ffa154631b
Revises: 1bf8e44d95e
Create Date: 2016-01-25 08:50:08.957814

"""

# revision identifiers, used by Alembic.
revision = '4ffa154631b'
down_revision = '1bf8e44d95e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
