"""empty message

Revision ID: 51b706eff65
Revises: None
Create Date: 2016-01-25 08:47:19.384635

"""

# revision identifiers, used by Alembic.
revision = '51b706eff65'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
