"""empty message

Revision ID: 52126c8a30e
Revises: 3b0521515ca
Create Date: 2016-01-25 08:48:24.077050

"""

# revision identifiers, used by Alembic.
revision = '52126c8a30e'
down_revision = '3b0521515ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
