"""empty message

Revision ID: 521ed22b68d
Revises: 34783216963
Create Date: 2016-01-25 08:48:52.771247

"""

# revision identifiers, used by Alembic.
revision = '521ed22b68d'
down_revision = '34783216963'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
