"""empty message

Revision ID: 526cc9db974
Revises: 2efe2037488
Create Date: 2016-01-25 08:48:45.579400

"""

# revision identifiers, used by Alembic.
revision = '526cc9db974'
down_revision = '2efe2037488'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'something')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('something', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
