"""empty message

Revision ID: 5f86ac3fe1
Revises: 521ed22b68d
Create Date: 2016-01-25 08:48:57.052105

"""

# revision identifiers, used by Alembic.
revision = '5f86ac3fe1'
down_revision = '521ed22b68d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
