"""empty message

Revision ID: 765a23fa25
Revises: 308d95eada6
Create Date: 2016-01-25 09:07:49.548648

"""

# revision identifiers, used by Alembic.
revision = '765a23fa25'
down_revision = '308d95eada6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
