"""empty message

Revision ID: b06c2d2b5
Revises: 44f9b10a927
Create Date: 2016-01-25 08:52:18.834517

"""

# revision identifiers, used by Alembic.
revision = 'b06c2d2b5'
down_revision = '44f9b10a927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
