"""empty message

Revision ID: d7cff3beda
Revises: b06c2d2b5
Create Date: 2016-01-25 08:53:09.425923

"""

# revision identifiers, used by Alembic.
revision = 'd7cff3beda'
down_revision = 'b06c2d2b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
