"""empty message

Revision ID: e8b14528b7
Revises: 24bac84032d
Create Date: 2016-01-25 08:55:08.445859

"""

# revision identifiers, used by Alembic.
revision = 'e8b14528b7'
down_revision = '24bac84032d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
